### ISSUE TITLE
Trouble loading data from firestore.

### ISSUE THREAD

**Issue by premy** [imenesesl/carousel_widget#20]
Not really an issue, but I was wondering wether you could show us how to get data in the fragments from firestore. Tried the following:
    `buildComunicados(context){
     print("buildComunicados called");
     return StreamBuilder<QuerySnapshot>(
      stream: Firestore.instance.collection("Noticias") 
      .orderBy('datum',descending: true).snapshots(),
      builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
        if (!snapshot.hasData)
          return Center(
            child: CircularProgressIndicator(),
          );
        else {
         

          return Carousel(
            listViews: snapshot.data.documents.map((doc) {
                return getFragment(doc);
              }).toList(),
          );
        }
      },
    );
    
  }
  getFragment(doc){
    return  Fragment(
                child: getScreen(doc),
              );
  }
  Widget getScreen(doc) {
    return new ListView(
      children: <Widget>[
        new Container(
          height: 250.0,
          margin: const EdgeInsets.fromLTRB(20.0, 90.0, 20.0, 0.0),
          child: Image.network(
            doc.data["image"],
          ),
        ),
        new Container(
          height: 45.0,
          margin: const EdgeInsets.fromLTRB(20.0, 8.0, 20.0, 0.0),
          child: Text(
           doc.data["title"],
            textAlign: TextAlign.center,
            overflow: TextOverflow.ellipsis,
            style: TextStyle(fontSize: 20),
          ),
        ),
        new Container(
          height: 100.0,
          margin: const EdgeInsets.fromLTRB(50.0, 12.0, 50.0, 0.0),
          child: Text(
            doc.data["description"],
            textAlign: TextAlign.center,
            overflow: TextOverflow.ellipsis,
            maxLines: 5,
            style: TextStyle(fontSize: 15),
          ),
        ),
      ],
    );
        }`
and the compiler complains: 

`type List<dynamic> is not a subtype of type List<Fragment>`

I like this carousel exactly because it allows for more than just images.
Thanks in advance
Formatting sucks, sorry; put the code inside the code block of the editor, but still...

**Comment by imenesesl** [comment]
Hi @premy thanks for sharing your problem, answering what you did, using firebase and firestore, I had the same error at the beginning but solved as follows
`snapshot.data.documents.map<Widget>`
If the problem persists I would like to deepen a little more with your help, thanks

**Comment by premy** [comment]
Ok, I updated the code like: snapshot.data.documents.map<Widget>
But then the compiler said: List<Widget>' is not a subtype of type 'List<Fragement>'.

So I said "allright, have it your way then" and I updated to snapshot.data.documents.map<Fragment>, and voilà! bugger works now.

Like I said, I couldn't find any flutter carousel slider capable of carrying along other content, besides the images. With this slider we can. Thanks a lot.
Btw, do you plan to add autoplay capabality in the near future? Would be awesome too.

**Comment by imenesesl** [comment]
fantastic, your solution gave me the initiative to add the
documentation in a very clear way and with respect to the
new feature, i will set the time for this list as soon as possible
