### ISSUE TITLE
Video with images in carousel

### ISSUE THREAD

**Issue by SalilThreeplus** [imenesesl/carousel_widget#25]
Hi,

How do I add video using videplayercontroller.network with images in carousel?

Help is appreciated, thanks.

**Comment by imenesesl** [comment]
Hi, you are using the package `video_player` truth?
The carousel receives a list of Fragments, that's fragments represent a widget,  thus, you can combine videos, pictures, and other widgets inside of fragment and the carousel will paint on the screen. @SalilThreeplus

**Comment by SalilThreeplus** [comment]
Yes I am using video_player and chewie package to render videos.
I have added video to carousal successfully thanks.
